# Generated by Django 3.2.25 on 2025-05-27 08:44

from django.db import migrations

from core.utils import insert_role_right_for_system, remove_role_right_for_system

ADMIN_ROLE_ID = 64
RIGHT_REPORT_ADD = 131224


def add_query_rights(apps, schema_editor):
    """
    Add gql_mutation_report_add_perms to the admin role.
    """
    insert_role_right_for_system(ADMIN_ROLE_ID, RIGHT_REPORT_ADD)


def remove_query_rights(apps, schema_editor):
    """
    Remove gql_mutation_report_add_perms to the admin role.
    """
    remove_role_right_for_system(ADMIN_ROLE_ID, RIGHT_REPORT_ADD)


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_add_query_rights'),
    ]

    operations = [
        migrations.RunPython(add_query_rights, remove_query_rights),
    ]
